### ISSUE TITLE
build/libs/goty-server-0.0.1-SNAPSHOT.jar

### ISSUE THREAD

**Issue by IrealiTY** [aleinin/game-of-the-year#36]
Hey I was trying to set up your server for a small group for friends as it seemed like a fun idea to run a local GOTY vote.
but building the docker fails at
` COPY failed: file not found in build context or excluded by .dockerignore: stat build/libs/goty-server-0.0.1-SNAPSHOT.jar: file does not exist` 
is this something that you could provide or was this app never intended for public use? :)

**Comment by aleinin** [comment]
Hey IrealityTY. 

I believe the issue with this is you just need to run a ./gradlew build 

With that said I asked @erichaagdev  and we think you're probably going to run into a few more issues, namely lacking IGDB data. I'll let him expand further if he wants but essentially right now a scraper is run to load data into Elasticsearch, then there is an IGDB webhook that updates whenever a new game is added. We don't currently we use the IGDB API natively (although we're discussing making that change)

From there, you'd run the frontend and backend and everything *should* work.

While it's exciting someone else may find a use for this admittedly specialized passion project, we haven't done a great job of making it easy to stand up. But we'd be happy to help you if you have any questions. 

I'll let @erichaagdev  expand on any specific steps you need to run the scraper as that was his area of expertise

**Comment by IrealiTY** [comment]
Thanks for the answer!

I managed to build the gradle and launch the frontend, and you said something about the elasticsearch is not behaving properly, search boxes just spin.

I didn't want to drop all the logs on you here only if either of you has the time and willpower to go through the troubleshooting :D

**Comment by aleinin** [comment]
Heya! I put up a PR I'm hoping @erichaagdev will be able to check out soon that will remove the dependency on Elastic Search and hit IGDB directly. This means you'll only need to provide your dev.twitch.tv id and secret in an .env file adjacent to the docker-compose. I'll put more detailed instructions once that PR gets approved

**Comment by aleinin** [comment]
Alrighty, pr merged. This means after doing the gradle build you should just able to stand everything up with docker compose and it'll work *fingers crossed* 

You will need to create a .env file adjacent to the goty-server Dockerfile with the TWITCH_CLIENT_ID and TWITCH_CLIENT_SECRET. If you're unsure about how to get those check out: https://api-docs.igdb.com/?javascript#account-creation

While I'd love to someday make this way more customizable in terms of presentation and questions asked, I don't see that changing in the next few weeks so you'll probably need to do some editing here or there in your fork

At the very least you'll probably want to change: https://github.com/aleinin/game-of-the-year/blob/main/goty-client/src/components/Header.tsx#L31

There are some minor things you can modify the functionality of with the constants file

https://github.com/aleinin/game-of-the-year/blob/main/goty-client/src/state/constants/reducer.ts#L17

That just requires a constants.json file in your public folder : https://github.com/aleinin/game-of-the-year/blob/main/goty-client/public/constants.json

Let me know if you have any questions along the way and i'm happy to help. Good luck!

**Comment by IrealiTY** [comment]
Heyo :) Thanks for the help!

I had to remove the test from the gradle build for it to successfully finish.
Docker deployment seemed fine, but seems like it still has issues and seems to look for elastic? (I did make sure i have the newest git pull)

Oh also had to change the URL in `src/components/App.tsx` as it was always looking for localhost
![image](https://user-images.githubusercontent.com/1223686/143460638-837fc0f5-a3d0-4a9b-afcd-b8e2ba2a03fa.png)

```
There was an unexpected error (type=Internal Server Error, status=500).
elasticsearch: System error
```

```
2021-11-25 14:37:46.576 ERROR 1 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception,
,
java.io.IOException: elasticsearch: System error,
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:854) ~[elasticsearch-rest-client-7.9.3.jar!/:7.9.3],
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:259) ~[elasticsearch-rest-client-7.9.3.jar!/:7.9.3],
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) ~[elasticsearch-rest-client-7.9.3.jar!/:7.9.3],
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1613) ~[elasticsearch-rest-high-level-client-7.9.3.jar!/:7.9.3],
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583) ~[elasticsearch-rest-high-level-client-7.9.3.jar!/:7.9.3],
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553) ~[elasticsearch-rest-high-level-client-7.9.3.jar!/:7.9.3],
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1069) ~[elasticsearch-rest-high-level-client-7.9.3.jar!/:7.9.3],
	at com.aleinin.goty.game.GameSearchService.search(GameSearchService.kt:27) ~[classes!/:na],
	at com.aleinin.goty.game.GameController.gameSearch(GameController.kt:21) ~[classes!/:na],
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na],
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na],
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na],
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na],
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.2.jar!/:5.3.2],
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.2.jar!/:5.3.2],
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.2.jar!/:5.3.2],
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.2.jar!/:5.3.2],
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.2.jar!/:5.3.2],
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.2.jar!/:5.3.2],
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1061) ~[spring-webmvc-5.3.2.jar!/:5.3.2],
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:961) ~[spring-webmvc-5.3.2.jar!/:5.3.2],
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.2.jar!/:5.3.2],
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.2.jar!/:5.3.2],
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) ~[tomcat-embed-core-9.0.41.jar!/:4.0.FR],
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.2.jar!/:5.3.2],
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.41.jar!/:4.0.FR],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.41.jar!/:9.0.41],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.2.jar!/:5.3.2],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar!/:5.3.2],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.2.jar!/:5.3.2],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar!/:5.3.2],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.2.jar!/:5.3.2],
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.2.jar!/:5.3.2],
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na],
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na],
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.41.jar!/:9.0.41],
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na],
```

**Comment by aleinin** [comment]
> Heyo :) Thanks for the help!
> 
> I had to remove the test from the gradle build for it to successfully finish. Docker deployment seemed fine, but seems like it still has issues and seems to look for elastic? (I did make sure i have the newest git pull)

If its still referencing elastic, it sounds like its an old image. I believe there is a docker compose command to force the image to be re-created but I don't know it off hand. I usually just delete the old image beforehand to force docker compose to recreate the image. There is no references to Elastic search in the current version so that's my best guess. 

Also, I fixed a bug this morning of 11/25 so you may need to pull from main again to get that fix relating to the year query param not working correctly 

> Oh also had to change the URL in `src/components/App.tsx` as it was always looking for localhost ![image](https://user-images.githubusercontent.com/1223686/143460638-837fc0f5-a3d0-4a9b-afcd-b8e2ba2a03fa.png)

You shouldn't need to change the App.tsx

https://github.com/aleinin/game-of-the-year/blob/main/goty-client/src/components/App.tsx#L45

It pulls the URL from constants.baseUrl

So if you're running dev (npm run start) just put "baseUrl": "https://myUrl.com" in the constants.json in the public folder

if you're running the production build, it should have a constants.json file in the build folder. 

Here is what mine looks like: 
![image](https://user-images.githubusercontent.com/25621595/143490603-1426bdfc-e957-4118-9c2c-df31edff7423.png)

**Comment by IrealiTY** [comment]
Right I forgot to do a `docker-compose build` to refresh the images
![image](https://user-images.githubusercontent.com/1223686/143501905-73071ef3-2876-4f2c-bd00-e8e3a1331bf0.png)

works now :) will now dig around and see how it works with the results etc

thanks a lot for your help!
